Update join_predictions.yml

diff --git a/.github/workflows/join_predictions.yml b/.github/workflows/join_predictions.yml
--- a/.github/workflows/join_predictions.yml
+++ b/.github/workflows/join_predictions.yml
@@ -27,23 +27,19 @@ jobs:
         run: |
           python join_predictions.py
 
-      - name: List files in predictions folder for debugging
-        run: |
-          ls -l predictions/
-
-      - name: Check if prediction_joined.db exists
+      - name: Verify database file creation
         run: |
           if [ -f "predictions/prediction_joined.db" ]; then
             echo "Joined prediction database found."
-
-            # Set up Git
-            git config --global user.name "GitHub Actions"
-            git config --global user.email "github-actions@github.com"
-
-            # Add and commit the new file to Git
-            git add predictions/prediction_joined.db
-            git commit -m "Update prediction joined database"
-            git push
           else
             echo "No prediction_joined.db file found, skipping commit"
+            exit 1  # Fail the workflow if the file is not found
           fi
+
+      - name: Commit and push changes
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "github-actions@github.com"
+          git add predictions/prediction_joined.db
+          git commit -m "Update prediction joined database"
+          git push
